# Generated by Django 3.1.7 on 2021-05-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='about',
            field=models.CharField(default='Please Complete this Section', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='darktheme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default='user27', max_length=255),
        ),
    ]
