# Generated by Django 3.1.7 on 2021-04-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210421_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
