# Generated by Django 3.1.7 on 2021-05-10 08:51

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210510_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_pic',
            field=models.ImageField(default='images/default.png', upload_to=accounts.models.upload_to, verbose_name='Image'),
        ),
    ]
