# Generated by Django 3.1.7 on 2021-05-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210513_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='about',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='darktheme',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='image',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
    ]
