# Generated by Django 3.1.7 on 2021-04-28 22:19

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_saved_object', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=255)),
                ('saved_data', jsonfield.fields.JSONField()),
            ],
        ),
    ]
