# Generated by Django 3.1.7 on 2021-04-29 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Scanner', '0002_savedobjects_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedobjects',
            old_name='saved_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='savedobjects',
            old_name='name_of_saved_object',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='savedobjects',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
