# Generated by Django 3.1.7 on 2021-05-08 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Scanner', '0004_auto_20210505_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedobjects',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
