# Generated by Django 3.1.7 on 2021-05-19 19:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Scanner', '0006_auto_20210508_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedobjects',
            name='data',
            field=jsonfield.fields.JSONField(unique=True),
        ),
    ]
